"""

Revision ID: 18efd54378a9
Revises:
Create Date: 2026-02-23 11:04:37.458289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "18efd54378a9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_model",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("serial_number", sa.String(length=255), nullable=False),
        sa.Column("rack_units", sa.Integer(), nullable=False),
        sa.Column("power_watts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "rack_model",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("serial_number", sa.String(length=255), nullable=False),
        sa.Column("total_units", sa.Integer(), nullable=False),
        sa.Column("max_power_watts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "rack_devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rack_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("start_unit", sa.Integer(), nullable=False),
        sa.Column("end_unit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device_model.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rack_id"], ["rack_model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rack_devices")
    op.drop_table("rack_model")
    op.drop_table("device_model")
    # ### end Alembic commands ###
